package yekonga

type DatabaseStructureType = map[string]map[string]map[string]interface{}

var DefaultTenantDatabaseStructure DatabaseStructureType = DatabaseStructureType{
	"Tenants": {
		"id":              {"type": "ID", "default": nil, "required": false},
		"userId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"name":            {"type": "String", "default": nil, "required": false},
		"description":     {"type": "String", "default": nil, "required": false},
		"logoUrl":         {"type": "URL", "default": nil, "required": false},
		"type":            {"type": "String", "default": "COMPANY", "required": false, "options": []string{"NGO", "COMPANY", "PRIVATE"}},
		"address":         {"type": "String", "default": nil, "required": false},
		"email":           {"type": "String", "default": nil, "required": false},
		"phone":           {"type": "String", "default": nil, "required": false},
		"website":         {"type": "String", "default": nil, "required": false},
		"domain":          {"type": "String", "default": nil, "required": false},
		"subdomain":       {"type": "String", "default": nil, "required": false},
		"defaultLanguage": {"type": "String", "default": "en", "required": false},
		"isApproved":      {"type": "Boolean", "default": false, "required": false},
		"status":          {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
		"createdAt":       {"type": "Date", "default": "now", "required": false},
	},
	"TenantConfigs": {
		"id":           {"type": "ID", "default": nil, "required": false},
		"tenantId":     {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"coreTheme":    {"type": "Any", "default": nil, "required": false},
		"darkTheme":    {"type": "Any", "default": nil, "required": false},
		"defaultTheme": {"type": "String", "default": "coreTheme", "required": false},
		"smtp":         {"type": "Any", "default": nil, "required": false},
		"sms":          {"type": "Any", "default": nil, "required": false},
		"whatsapp":     {"type": "Any", "default": nil, "required": false},
	},
	"TenantFeatures": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"tenantId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"moduleName":  {"type": "String", "default": nil, "required": false},
		"featureCode": {"type": "String", "default": nil, "required": false},
		"enabled":     {"type": "Boolean", "default": true, "required": false},
	},
	"TenantUsers": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"tenantId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"userId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"role":      {"type": "String", "default": "user", "required": false, "options": []string{"manager", "user"}},
		"status":    {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
		"createdAt": {"type": "Date", "default": "now", "required": false},
	},
}

var DefaultTenantCatchDatabaseStructure DatabaseStructureType = DatabaseStructureType{
	"TenantCatches": {
		"id":       {"type": "ID", "default": nil, "required": false},
		"tenantId": {"type": "ID", "default": nil, "required": false},
		"domain":   {"type": "String", "default": nil, "required": false},
	},
}

var DefaultAuthDatabaseStructure DatabaseStructureType = DatabaseStructureType{
	"Users": {
		"id":                 {"type": "ID", "default": nil, "required": false},
		"tenantId":           {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"firstName":          {"type": "String", "default": nil, "required": false},
		"secondName":         {"type": "String", "default": nil, "required": false},
		"lastName":           {"type": "String", "default": nil, "required": false},
		"username":           {"type": "String", "default": nil, "required": false},
		"usernameType":       {"type": "String", "default": nil, "required": false, "options": []string{"name", "email", "phone", "whatsapp"}},
		"email":              {"type": "String", "default": nil, "required": false},
		"phone":              {"type": "String", "default": nil, "required": false},
		"whatsapp":           {"type": "String", "default": nil, "required": false},
		"profileUrl":         {"type": "URL", "default": nil, "required": false},
		"gender":             {"type": "String", "default": nil, "required": false, "options": []string{"male", "female"}},
		"dateOfBirth":        {"type": "Date", "default": nil, "required": false},
		"password":           {"type": "String", "default": nil, "required": false, "protected": true},
		"role":               {"type": "String", "default": nil, "required": false, "options": []string{"admin", "user"}},
		"token":              {"type": "String", "default": nil, "required": false},
		"googleToken":        {"type": "String", "default": nil, "required": false},
		"rememberToken":      {"type": "String", "default": nil, "required": false},
		"deviceToken":        {"type": "String", "default": nil, "required": false},
		"status":             {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
		"isActive":           {"type": "Boolean", "default": false, "required": false},
		"isBanned":           {"type": "Boolean", "default": false, "required": false},
		"isPhoneVerified":    {"type": "Boolean", "default": false, "required": false},
		"phoneVerifyCode":    {"type": "String", "default": false, "required": false, "protected": true},
		"phoneVerifiedAt":    {"type": "Date", "default": nil, "required": false},
		"isEmailVerified":    {"type": "Boolean", "default": false, "required": false},
		"emailVerifyCode":    {"type": "String", "default": false, "required": false, "protected": true},
		"emailVerifiedAt":    {"type": "Date", "default": nil, "required": false},
		"isWhatsappVerified": {"type": "Boolean", "default": false, "required": false},
		"whatsappVerifyCode": {"type": "String", "default": false, "required": false, "protected": true},
		"whatsappVerifiedAt": {"type": "Date", "default": nil, "required": false},
		"otpCode":            {"type": "String", "default": nil, "required": false, "protected": true},
		"otpCreatedAt":       {"type": "Date", "default": nil, "required": false},
		"userType": {
			"type":     "String",
			"default":  "individual",
			"required": false,
			"options":  []string{"individual", "organization"},
		},
		"lastActive": {"type": "Date", "default": "now", "required": false},
		"createdAt":  {"type": "Date", "default": "now", "required": false},
		"updatedAt":  {"type": "Date", "default": "now", "required": false},
		"deletedAt":  {"type": "Date", "default": nil, "required": false},
	},
	"Profiles": {
		"id":              {"type": "ID", "default": nil, "required": false},
		"tenantId":        {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"userId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"name":            {"type": "String", "default": nil, "required": false},
		"description":     {"type": "String", "default": nil, "required": false},
		"profileUrl":      {"type": "URL", "default": nil, "required": false},
		"type":            {"type": "String", "default": nil, "required": false, "options": []string{"admin", "manager", "user"}},
		"address":         {"type": "String", "default": nil, "required": false},
		"email":           {"type": "String", "default": nil, "required": false},
		"phone":           {"type": "String", "default": nil, "required": false},
		"website":         {"type": "String", "default": nil, "required": false},
		"domain":          {"type": "String", "default": nil, "required": false},
		"subdomain":       {"type": "String", "default": nil, "required": false},
		"defaultLanguage": {"type": "String", "default": "en", "required": false},
		"isPrivate":       {"type": "Boolean", "default": false, "required": false},
		"isApproved":      {"type": "Boolean", "default": false, "required": false},
		"status":          {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
		"deletedAt":       {"type": "Date", "default": "now", "required": false},
	},
	"ProfileUsers": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"tenantId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId": {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"role":      {"type": "String", "default": nil, "required": false, "options": []string{"manager", "user"}},
		"status":    {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
		"createdAt": {"type": "Date", "default": "now", "required": false},
	},
	"RefreshTokens": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"tenantId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"domain":    {"type": "String", "default": nil, "required": false},
		"profileId": {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"adminId":   {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"tokenHash": {"type": "String", "default": nil, "required": false},
		"userAgent": {"type": "String", "default": nil, "required": false},
		"ipAddress": {"type": "String", "default": nil, "required": false},
		"revoked":   {"type": "Boolean", "default": false, "required": false},
		"expiresAt": {"type": "Date", "default": "now", "required": false},
		// 	"roles":       make([]string, 0), // ["admin", "finance"],
		// 	"permissions": make([]string, 0), // ["payroll.read", "asset.write"],
	},
	"LoginAttempts": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"tenantId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"domain":    {"type": "String", "default": nil, "required": false},
		"profileId": {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"username":  {"type": "String", "default": "active", "required": false, "options": []string{"success", "fail"}},
		"status":    {"type": "String", "default": "active", "required": false, "options": []string{"success", "fail"}},
		"timestamp": {"type": "Date", "default": "now", "required": false},
	},
	"UserDevices": {
		"id":         {"type": "ID", "default": nil, "required": false},
		"tenantId":   {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"userId":     {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"deviceUuid": {"type": "String", "default": nil, "required": false},
		"type":       {"type": "Any", "default": nil, "required": false},
		"info":       {"type": "Any", "default": nil, "required": false},
		"status":     {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
		"createdAt":  {"type": "Date", "default": "now", "required": false},
	},
	"UserDeviceCommands": {
		"id":           {"type": "ID", "default": nil, "required": false},
		"tenantId":     {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"userDeviceId": {"type": "ID", "default": nil, "required": false, "foreignKey": "UserDevice.id"},
		"deviceUuid":   {"type": "String", "default": nil, "required": false},
		"action":       {"type": "String", "default": nil, "required": false},
		"type": {
			"type":     "String",
			"default":  "command",
			"required": false,
			"options":  []string{"command", "notification", "chat"},
		},
		"isSent":     {"type": "Boolean", "default": false, "required": false},
		"isReceived": {"type": "Boolean", "default": false, "required": false},
		"createdAt":  {"type": "Date", "default": "now", "required": false},
	},
	"AuthPermissions": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"moduleName":  {"type": "String", "default": nil, "required": false},
		"group":       {"type": "String", "default": nil, "required": false},
		"code":        {"type": "String", "default": nil, "required": false},
		"name":        {"type": "String", "default": nil, "required": false},
		"description": {"type": "String", "default": nil, "required": false},
		"isVisible":   {"type": "Boolean", "default": true, "required": false},
	},
	"AuthGroups": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"tenantId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId":   {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"moduleName":  {"type": "String", "default": nil, "required": false},
		"name":        {"type": "String", "default": nil, "required": false},
		"description": {"type": "String", "default": nil, "required": false},
	},
	"AuthGroupPermissions": {
		"id":               {"type": "ID", "default": nil, "required": false},
		"tenantId":         {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"authGroupId":      {"type": "ID", "default": nil, "required": false, "foreignKey": "AuthGroup.id"},
		"authPermissionId": {"type": "ID", "default": nil, "required": false, "foreignKey": "AuthPermission.id"},
	},
	"AuthUserPermissions": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"tenantId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId":   {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":      {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"authGroupId": {"type": "ID", "default": nil, "required": false, "foreignKey": "AuthGroup.id"},
		"moduleName":  {"type": "String", "default": nil, "required": false},
		"code":        {"type": "String", "default": nil, "required": false},
	},
	"TranslatorLanguages": {
		"id":     {"type": "ID", "default": nil, "required": false},
		"locale": {"type": "String", "default": nil, "required": false},
		"name":   {"type": "String", "default": nil, "required": false},
		"flag":   {"type": "String", "default": nil, "required": false},
		"status": {"type": "String", "default": "active", "required": false, "options": []string{"active", "inactive"}},
	},
	"TranslatorTranslations": {
		"id":                   {"type": "ID", "default": nil, "required": false},
		"translatorLanguageId": {"type": "ID", "default": nil, "required": false, "foreignKey": "TranslatorLanguage.id"},
		"locale":               {"type": "String", "default": nil, "required": false},
		"moduleName":           {"type": "String", "default": nil, "required": false},
		"group":                {"type": "String", "default": nil, "required": false},
		"item":                 {"type": "String", "default": nil, "required": false},
		"description":          {"type": "String", "default": nil, "required": false},
		"text":                 {"type": "String", "default": nil, "required": false},
		"unstable":             {"type": "String", "default": nil, "required": false},
		"locked":               {"type": "String", "default": nil, "required": false},
	},
	"Locations": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"parentId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Location.id"},
		"name":      {"type": "String", "default": nil, "required": false},
		"shortCode": {"type": "String", "default": nil, "required": false},
		"phoneCode": {"type": "String", "default": nil, "required": false},
		"currency":  {"type": "String", "default": nil, "required": false},
		"flag":      {"type": "String", "default": nil, "required": false},
		"type": {
			"type":     "String",
			"default":  "region",
			"required": false,
			"options":  []string{"country", "region", "district", "ward"},
		},
		"latitude":  {"type": "Float", "default": nil, "required": false},
		"longitude": {"type": "Float", "default": nil, "required": false},
	},
}

var DefaultBillingDatabaseStructure DatabaseStructureType = DatabaseStructureType{
	"Modules": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"moduleName":  {"type": "String", "default": nil, "required": false},
		"title":       {"type": "String", "default": nil, "required": false},
		"description": {"type": "String", "default": nil, "required": false},
		"enabled":     {"type": "Boolean", "default": true, "required": false},
	},
	"PricingPlans": {
		"id":           {"type": "ID", "default": nil, "required": false},
		"moduleId":     {"type": "ID", "default": nil, "required": false, "foreignKey": "Module.id"},
		"pricingType":  {"type": "String", "default": "flat", "required": false, "options": []string{"flat", "per_user", "per_unit", "metered"}},
		"billingCycle": {"type": "String", "default": "flat", "required": false, "options": []string{"monthly", "yearly"}},
		"price":        {"type": "Float", "default": 0, "required": false},
		"trialDays":    {"type": "Number", "default": 30, "required": false},
		"graceDays":    {"type": "Number", "default": 7, "required": false},
	},
	"Subscriptions": {
		"id":                 {"type": "ID", "default": nil, "required": false},
		"tenantId":           {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"status":             {"type": "String", "default": "flat", "required": false, "options": []string{"active", "grace", "trailing", "past_due", "canceled", "unpaid", "expired"}},
		"trialStart":         {"type": "Date", "default": nil, "required": false},
		"trialEnd":           {"type": "Date", "default": nil, "required": false},
		"currentPeriodStart": {"type": "Date", "default": nil, "required": false},
		"currentPeriodEnd":   {"type": "Date", "default": nil, "required": false},
		"gracePeriodEnd":     {"type": "Date", "default": nil, "required": false},
		"nextBillingDate":    {"type": "Date", "default": nil, "required": false},
		"canceledAt":         {"type": "Date", "default": nil, "required": false},
	},
	"SubscriptionItems": {
		"id":             {"type": "ID", "default": nil, "required": false},
		"tenantId":       {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"subscriptionId": {"type": "ID", "default": nil, "required": false, "foreignKey": "Subscription.id"},
		"moduleId":       {"type": "ID", "default": nil, "required": false, "foreignKey": "Module.id"},
		"pricingPlanId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "PricingPlan.id"},
		"quantity":       {"type": "Float", "default": 0, "required": false},
	},
	"UsageRecords": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"tenantId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"moduleId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "Module.id"},
		"quantity":    {"type": "Float", "default": 0, "required": false},
		"periodStart": {"type": "Date", "default": nil, "required": false},
		"periodEnd":   {"type": "Date", "default": nil, "required": false},
	},
	"Invoices": {
		"id":              {"type": "ID", "default": nil, "required": false},
		"tenantId":        {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"subscriptionId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Subscription.id"},
		"amountDue":       {"type": "Float", "default": 0, "required": false},
		"amountPaid":      {"type": "Float", "default": 0, "required": false},
		"amountRemaining": {"type": "Float", "default": 0, "required": false},
		"status":          {"type": "String", "default": "flat", "required": false, "options": []string{"paid", "pending", "partially_paid", "failed", "canceled"}},
		"dueDate":         {"type": "Date", "default": nil, "required": false},
		"paidDate":        {"type": "Date", "default": nil, "required": false},
	},
	"InvoiceItems": {
		"id":                 {"type": "ID", "default": nil, "required": false},
		"tenantId":           {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"invoiceId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "Invoice.id"},
		"moduleId":           {"type": "ID", "default": nil, "required": false, "foreignKey": "Module.id"},
		"subscriptionItemId": {"type": "ID", "default": nil, "required": false, "foreignKey": "SubscriptionItem.id"},
		"description":        {"type": "String", "default": nil, "required": false},
		"pricingType":        {"type": "String", "default": "flat", "required": false, "options": []string{"flat", "per_user", "per_unit", "metered"}},
		"quantity":           {"type": "Float", "default": 0, "required": false},
		"unitPrice":          {"type": "Float", "default": 0, "required": false},
		"totalPrice":         {"type": "Float", "default": 0, "required": false},
		"currency":           {"type": "String", "default": nil, "required": false},
		"startPeriod":        {"type": "Date", "default": nil, "required": false},
		"endPeriod":          {"type": "Date", "default": nil, "required": false},
		"metadata":           {"type": "Any", "default": nil, "required": false},
		"createdAt":          {"type": "Date", "default": "now", "required": false},
	},
	"Payments": {
		"id":                {"type": "ID", "default": nil, "required": false},
		"tenantId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"provider":          {"type": "String", "default": nil, "required": false},
		"providerPaymentId": {"type": "String", "default": nil, "required": false},
		"amount":            {"type": "Float", "default": 0, "required": false},
		"currency":          {"type": "String", "default": nil, "required": false},
		"status":            {"type": "String", "default": "flat", "required": false, "options": []string{"pending", "succeeded", "failed", "canceled", "refunded"}},
		"paymentMethod":     {"type": "String", "default": "flat", "required": false, "options": []string{"card", "bank_transfer", "paypal", "crypto"}},
		"failureReason":     {"type": "String", "default": nil, "required": false},
		"paidAt":            {"type": "Date", "default": "now", "required": false},
		"refundedAt":        {"type": "Date", "default": nil, "required": false},
		"metadata":          {"type": "Any", "default": nil, "required": false},
		"updatedAt":         {"type": "Date", "default": "now", "required": false},
		"createdAt":         {"type": "Date", "default": "now", "required": false},
	},
	"PaymentAllocations": {
		"id":              {"type": "ID", "default": nil, "required": false},
		"tenantId":        {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"paymentId":       {"type": "String", "default": nil, "required": false, "foreignKey": "Payments.id"},
		"invoiceId":       {"type": "String", "default": nil, "required": false, "foreignKey": "Invoice.id"},
		"amountAllocated": {"type": "Float", "default": 0, "required": false},
		"createdAt":       {"type": "Date", "default": "now", "required": false},
	},
	"AccountCredits": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"tenantId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"paymentId": {"type": "String", "default": nil, "required": false, "foreignKey": "Payments.id"},
		"amount":    {"type": "Float", "default": 0, "required": false},
		"createdAt": {"type": "Date", "default": "now", "required": false},
	},
}

var DefaultExtraDatabaseStructure DatabaseStructureType = DatabaseStructureType{
	"Notifications": {
		"id":                {"type": "ID", "default": nil, "required": false},
		"tenantId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId":         {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":            {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"senderName":        {"type": "String", "default": nil, "required": false},
		"referenceId":       {"type": "ID", "default": nil, "required": false},
		"referenceName":     {"type": "String", "default": nil, "required": false},
		"recipient":         {"type": "String", "default": nil, "required": false},
		"recipientName":     {"type": "String", "default": nil, "required": false},
		"replyTo":           {"type": "String", "default": nil, "required": false},
		"title":             {"type": "String", "default": nil, "required": false},
		"content":           {"type": "Any", "default": nil, "required": false},
		"link":              {"type": "String", "default": nil, "required": false},
		"attachment":        {"type": "String", "default": nil, "required": false},
		"trackingCode":      {"type": "String", "default": nil, "required": false},
		"type":              {"type": "String", "default": nil, "required": false, "options": []string{"mail", "sms", "push"}},
		"isSeen":            {"type": "Boolean", "default": false, "required": false},
		"status":            {"type": "String", "default": nil, "required": false, "options": []string{"submitted", "waiting", "delivered", "undelivered"}},
		"response":          {"type": "Any", "default": nil, "required": false},
		"responseReference": {"type": "String", "default": nil, "required": false},
		"timestamp":         {"type": "Date", "default": "now", "required": false},
	},
	"PushNotifications": {
		"id":             {"type": "ID", "default": nil, "required": false},
		"tenantId":       {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId":      {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":         {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"deviceId":       {"type": "ID", "default": nil, "required": false, "foreignKey": "UserDevice.id"},
		"title":          {"type": "String", "default": nil, "required": false},
		"body":           {"type": "String", "default": nil, "required": false},
		"iconUrl":        {"type": "URL", "default": nil, "required": false},
		"pictureUrl":     {"type": "URL", "default": nil, "required": false},
		"payload":        {"type": "String", "default": nil, "required": false},
		"action":         {"type": "String", "default": nil, "required": false},
		"actionTargetId": {"type": "Any", "default": nil, "required": false},
		"isDelivered":    {"type": "Boolean", "default": nil, "required": false},
		"status":         {"type": "String", "default": nil, "required": false, "options": []string{"waiting", "sent", "delivered"}},
		"createdAt":      {"type": "Date", "default": "now", "required": false},
		"updatedAt":      {"type": "Date", "default": "now", "required": false},
	},
	"SocketMessages": {
		"id":        {"type": "ID", "default": nil, "required": false},
		"tenantId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId": {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"deviceId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "UserDevice.id"},
		"namespace": {"type": "String", "default": nil, "required": false},
		"action":    {"type": "String", "default": nil, "required": false},
		"content":   {"type": "Any", "default": nil, "required": false},
		"status":    {"type": "String", "default": nil, "required": false, "options": []string{"waiting", "sent", "delivered"}},
		"createdAt": {"type": "Date", "default": "now", "required": false},
		"updatedAt": {"type": "Date", "default": "now", "required": false},
	},
	"AuditTrails": {
		"id":         {"type": "ID", "default": nil, "required": false},
		"tenantId":   {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId":  {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"userId":     {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"action":     {"type": "String", "default": nil, "required": false},
		"documentId": {"type": "ID", "default": nil, "required": false},
		"collection": {"type": "String", "default": nil, "required": false},
		"model":      {"type": "String", "default": nil, "required": false},
		"newValues":  {"type": "Any", "default": nil, "required": false},
		"oldValues":  {"type": "Any", "default": nil, "required": false},
		"ipAddress":  {"type": "String", "default": nil, "required": false},
		"browser":    {"type": "Any", "default": nil, "required": false},
		"userAgent":  {"type": "String", "default": nil, "required": false},
		"createdAt":  {"type": "Date", "default": "now", "required": false},
	},
	"Reports": {
		"id":          {"type": "ID", "default": nil, "required": false},
		"tenantId":    {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"userId":      {"type": "ID", "default": nil, "required": false, "foreignKey": "User.id"},
		"profileId":   {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"name":        {"type": "String", "default": nil, "required": false},
		"description": {"type": "String", "default": nil, "required": false},
		"data":        {"type": "Any", "default": nil, "required": false},
		"isPrivate":   {"type": "Boolean", "default": nil, "required": false},
		"isDashboard": {"type": "Boolean", "default": nil, "required": false},
		"sendEmail":   {"type": "Boolean", "default": nil, "required": false},
		"emails":      {"type": "Any", "default": nil, "required": false},
		"createdAt":   {"type": "Date", "default": "now", "required": false},
	},
	"ChatGroups": {
		"id":              {"type": "ID", "default": nil, "required": false},
		"tenantId":        {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"profileId":       {"type": "ID", "default": nil, "required": false, "foreignKey": "Profile.id"},
		"parentReference": {"type": "ID", "default": nil, "required": false},
		"reference":       {"type": "ID", "default": nil, "required": false},
		"title":           {"type": "String", "default": nil, "required": false},
		"description":     {"type": "String", "default": nil, "required": false},
		"members":         {"type": "{ID}", "default": []string{}, "required": false, "foreignKey": "ChatGroupMember"},
		"type": {
			"type":     "String",
			"default":  "public",
			"required": false,
			"options":  []string{"private", "public", "general"},
		},
		"timestamp": {"type": "Date", "default": "now", "required": false},
	},
	"ChatGroupMembers": {
		"id":              {"type": "ID", "default": nil, "required": false},
		"tenantId":        {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"reference":       {"type": "ID", "default": nil, "required": false},
		"userId":          {"type": "ID", "default": nil, "required": false, "resource": "Users.id"},
		"userReferenceId": {"type": "ID", "default": nil, "required": false},
		"name":            {"type": "String", "default": nil, "required": false},
		"profileUrl":      {"type": "String", "default": nil, "required": false},
		"isAdmin":         {"type": "Boolean", "default": false, "required": false},
		"isOwner":         {"type": "Boolean", "default": false, "required": false},
		"timestamp":       {"type": "Date", "default": "now", "required": false},
	},
	"ChatMessages": {
		"id":                {"type": "ID", "default": nil, "required": false},
		"tenantId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"chatGroupId":       {"type": "ID", "default": nil, "required": false, "foreignKey": "ChatGroup"},
		"chatGroupMemberId": {"type": "ID", "default": nil, "required": false, "foreignKey": "ChatGroupMember.id"},
		"content":           {"type": "String", "default": nil, "required": false},
		"media":             {"type": "Any", "default": nil, "required": false},
		"mediaReference":    {"type": "String", "default": nil, "required": false},
		"type": {
			"type":     "String",
			"default":  "active",
			"required": false,
			"options":  []string{"text", "image", "location", "document", "video", "audio"},
		},
		"timestamp": {"type": "Date", "default": "now", "required": false},
	},
	"ChatMessageStates": {
		"id":                {"type": "ID", "default": nil, "required": false},
		"tenantId":          {"type": "ID", "default": nil, "required": false, "foreignKey": "Tenant.id"},
		"chatMessageId":     {"type": "ID", "default": nil, "required": false, "foreignKey": "ChatMessage.id"},
		"chatGroupMemberId": {"type": "ID", "default": nil, "required": false, "foreignKey": "ChatGroupMember.id"},
		"sent":              {"type": "Boolean", "default": false, "required": false},
		"sentDate":          {"type": "Date", "default": nil, "required": false},
		"received":          {"type": "Boolean", "default": false, "required": false},
		"receivedDate":      {"type": "Date", "default": nil, "required": false},
		"opened":            {"type": "Boolean", "default": false, "required": false},
		"openedDate":        {"type": "Date", "default": nil, "required": false},
		"timestamp":         {"type": "Date", "default": "now", "required": false},
	},
}
